import { describe, expect, it } from "vitest";
import {
  conciseVocabularyLimits,
  createFingerprint,
  groupFreeModelsForOpenRouter,
  hasSyncableVocabularyChanges,
  hasDriveConflict,
  isConciseVocabularyEntry,
  isFreeOnlyModel,
  mergeVocabularyEntries,
  normalizeOpenRouterApiKey,
  normalizeWords,
  parseGeneratedVocabularyEntries,
  parseVocabularyMarkdown,
  freeModelFallbacks,
  renderVocabularyMarkdown,
  requestWithFreeModelRouter,
} from "./vocabulary";

describe("vocabulary helpers", () => {
  it("normalizes batch input and removes duplicates", () => {
    expect(normalizeWords("Serenity, grit\nserenity\n  epiphany ")).toEqual([
      "Serenity",
      "grit",
      "epiphany",
    ]);
  });

  it("renders and parses the established three-column Markdown table", () => {
    const markdown = renderVocabularyMarkdown([
      {
        id: "serenity-1",
        word: "Serenity",
        meaning: "A calm and peaceful state",
        example: "The garden gave her serenity.",
        createdAt: 0,
      },
    ]);

    expect(markdown).toContain("| Word or Phrase | Simple Meaning | Example |");
    expect(parseVocabularyMarkdown(markdown)).toMatchObject([
      { word: "Serenity", meaning: "A calm and peaceful state" },
    ]);
  });

  it("prevents duplicate words during a merge", () => {
    const result = mergeVocabularyEntries(
      [{ id: "1", word: "serenity", meaning: "calm", example: "Example.", createdAt: 0 }],
      [
        { id: "2", word: "Serenity", meaning: "calm", example: "Example.", createdAt: 0 },
        { id: "3", word: "Grit", meaning: "courage", example: "Example.", createdAt: 0 },
      ],
    );

    expect(result.entries).toHaveLength(2);
    expect(result.duplicates).toEqual(["Serenity"]);
  });

  it("changes the fingerprint when the Drive content changes", () => {
    expect(createFingerprint("first revision")).toBe(createFingerprint("first revision"));
    expect(createFingerprint("first revision")).not.toBe(createFingerprint("edited revision"));
  });

  it("flags a changed Drive revision or file body before sync", () => {
    const expected = { version: "12", fingerprint: createFingerprint("saved file") };
    expect(hasDriveConflict(expected, { version: "12", content: "saved file" })).toBe(false);
    expect(hasDriveConflict(expected, { version: "13", content: "saved file" })).toBe(true);
    expect(hasDriveConflict(expected, { version: "12", content: "edited in Obsidian" })).toBe(true);
  });

  it("uses five explicit verified free candidates and excludes the random free-model router", () => {
    expect(freeModelFallbacks).toHaveLength(5);
    expect(freeModelFallbacks.every(isFreeOnlyModel)).toBe(true);
    expect(freeModelFallbacks).not.toContain("openrouter/free");
    expect(freeModelFallbacks).toContain("google/gemma-4-26b-a4b-it:free");
    expect(freeModelFallbacks).toContain("openai/gpt-oss-20b:free");
    expect(isFreeOnlyModel("paid/provider-model")).toBe(false);
  });

  it("splits five free candidates into OpenRouter-compatible groups of at most three", () => {
    expect(groupFreeModelsForOpenRouter(["one:free", "two:free", "three:free", "four:free", "five:free"]))
      .toEqual([["one:free", "two:free", "three:free"], ["four:free", "five:free"]]);
  });

  it("normalizes a raw or accidentally prefixed OpenRouter key without exposing its value", () => {
    expect(normalizeOpenRouterApiKey("  sk-or-v1-example  ")).toBe("sk-or-v1-example");
    expect(normalizeOpenRouterApiKey("Bearer sk-or-v1-example\n")).toBe("sk-or-v1-example");
  });

  it("retries one transient multi-model request while preserving the complete free candidate list", async () => {
    const calls: string[][] = [];
    const result = await requestWithFreeModelRouter(
      async models => {
        calls.push([...models]);
        if (calls.length === 1) throw new Error("OpenRouter 429: capacity temporarily busy");
        return "generated";
      },
      ["first:free", "second:free", "paid/provider-model"],
      0,
    );

    expect(result).toEqual({
      value: "generated",
      attempts: 2,
      candidates: ["first:free", "second:free"],
    });
    expect(calls).toEqual([["first:free", "second:free"], ["first:free", "second:free"]]);
  });

  it("uses the next compatible free-model group only after a retryable first group is exhausted", async () => {
    const calls: string[][] = [];
    const result = await requestWithFreeModelRouter(
      async models => {
        calls.push([...models]);
        if (models.includes("first:free")) throw new Error("OpenRouter 503: temporarily busy");
        return "generated by overflow group";
      },
      ["first:free", "second:free", "third:free", "fourth:free", "fifth:free"],
      0,
    );

    expect(result.value).toBe("generated by overflow group");
    expect(result.attempts).toBe(3);
    expect(calls).toEqual([
      ["first:free", "second:free", "third:free"],
      ["first:free", "second:free", "third:free"],
      ["fourth:free", "fifth:free"],
    ]);
  });

  it("retries malformed free-model output once instead of surfacing it immediately", async () => {
    let calls = 0;
    const result = await requestWithFreeModelRouter(
      async () => {
        calls += 1;
        if (calls === 1) throw new Error("Model response was not valid JSON.");
        return "repaired";
      },
      ["only:free"],
      0,
    );

    expect(result.value).toBe("repaired");
    expect(result.attempts).toBe(2);
  });

  it("keeps an authentication failure specific instead of wasting a retry", async () => {
    await expect(requestWithFreeModelRouter(
      async () => { throw new Error("OpenRouter 401: invalid API key"); },
      ["only:free"],
      0,
    )).rejects.toThrow("OpenRouter 401: invalid API key");
  });

  it("accepts compact vocabulary notes and rejects overlong model output", () => {
    expect(isConciseVocabularyEntry({
      word: "hypothesis",
      meaning: "A testable idea based on evidence.",
      example: "The researcher tested her hypothesis.",
    })).toBe(true);

    expect(isConciseVocabularyEntry({
      word: "hypothesis",
      meaning: "A proposed explanation based on limited evidence that can be tested through observation.",
      example: "The researcher formed a hypothesis that adding fertilizer would increase crop yield.",
    })).toBe(false);
    expect(conciseVocabularyLimits.meaningWords).toBe(8);
    expect(conciseVocabularyLimits.exampleWords).toBe(10);
  });

  it("parses valid JSON even when a free model wraps it in a Markdown fence", () => {
    expect(parseGeneratedVocabularyEntries("```json\n{\"entries\":[{\"word\":\"test\",\"meaning\":\"A check.\",\"example\":\"We took a test.\"}]}\n```"))
      .toEqual([{ word: "test", meaning: "A check.", example: "We took a test." }]);
  });

  it("rejects malformed or empty free-model output so another free model can be tried", () => {
    expect(() => parseGeneratedVocabularyEntries("not JSON")).toThrow("not valid JSON");
    expect(() => parseGeneratedVocabularyEntries('{"entries":[]}')).toThrow("usable vocabulary entries");
  });

  it("allows a sync after a Library edit or deletion even with no new drafts", () => {
    expect(hasSyncableVocabularyChanges([], true)).toBe(true);
    expect(hasSyncableVocabularyChanges([], false)).toBe(false);
    expect(hasSyncableVocabularyChanges([
      { id: "draft-1", word: "hypothesis", meaning: "A testable idea.", example: "We tested the hypothesis.", createdAt: 0 },
    ], false)).toBe(true);
  });
});
